import {beforeEach,describe,it,expect} from 'vitest';
import {prisma} from '@/lib/db';
import {resetDb,seedBasics,type Basics} from './helpers/db';
import {deleteCampaignPermanently} from '@/lib/campaign-delete';
import type {SessionUser} from '@/lib/auth/current-user';
let b:Basics,user:SessionUser;
beforeEach(async()=>{await resetDb();b=await seedBasics();user={...b.users.ria,podIds:[],pods:[]};});
const campaign=()=>prisma.campaign.create({data:{name:'Erase this campaign',sequenceId:b.sequence.id,podId:b.pods.Alisa.id,personIds:['person-01'],startDate:'2027-01-04',status:'STOPPED'}});
describe('explicit campaign erasure',()=>{
 it('requires an admin, exact name and a non-running campaign',async()=>{const c=await campaign();await expect(deleteCampaignPermanently(c.id,c.name,{...user,role:'BIZ_OPS'})).rejects.toThrow(/admin/);await expect(deleteCampaignPermanently(c.id,'wrong',user)).rejects.toThrow(/exact/);await prisma.campaign.update({where:{id:c.id},data:{status:'ACTIVE'}});await expect(deleteCampaignPermanently(c.id,c.name,user)).rejects.toThrow(/Stop/);expect(await prisma.campaign.count()).toBe(1);});
 it('erases dependent work, audit and outbox without deleting people or another campaign',async()=>{const c=await campaign();const other=await prisma.campaign.create({data:{name:'Keep me',sequenceId:b.sequence.id,podId:b.pods.Alisa.id,startDate:'2027-02-01'}});const e=await prisma.enrollment.create({data:{campaignId:c.id,personId:'person-01',foUserId:b.users.alisa.id,sequenceId:b.sequence.id,startDate:c.startDate,status:'EXITED'}});const t=await prisma.task.create({data:{enrollmentId:e.id,foUserId:b.users.alisa.id,stepIndex:0,stepId:'s',stepDay:1,actionIndex:0,actionId:'a',action:'EMAIL',label:'Email',dueDate:c.startDate,plannedDate:c.startDate,dueAt:new Date('2027-01-04T15:00Z'),state:'CANCELLED'}});await prisma.twentyWrite.create({data:{operation:'createTask',objectType:'task',taskId:t.id,payload:{title:'Old task'},status:'FAILED'}});await prisma.touch.create({data:{personId:'person-01',channel:'EMAIL',direction:'OUTBOUND',occurredAt:new Date(),summary:'Campaign email',externalId:`task:${t.id}`}});await prisma.auditLog.create({data:{entityType:'task',entityId:t.id,action:'created',actorType:'SYSTEM',details:{campaignId:c.id}}});await deleteCampaignPermanently(c.id,c.name,user);expect(await prisma.campaign.findUnique({where:{id:c.id}})).toBeNull();expect(await prisma.campaign.findUnique({where:{id:other.id}})).not.toBeNull();expect(await prisma.task.count()).toBe(0);expect(await prisma.enrollment.count()).toBe(0);expect(await prisma.twentyWrite.count()).toBe(0);expect(await prisma.touch.count()).toBe(0);expect(await prisma.personCache.findUnique({where:{id:'person-01'}})).not.toBeNull();expect(await prisma.sequence.findUnique({where:{id:b.sequence.id}})).not.toBeNull();expect(await prisma.auditLog.count({where:{entityId:t.id}})).toBe(0);});
});
