import {describe,it,expect} from 'vitest';
import {fitCampaignStarter,outreachLimits} from '@/lib/campaign-starter';
import {outreachRecipe} from '@/lib/campaign-starter';
import {buildCampaignCalendar,type CampaignDraft} from '@/lib/campaign-planner';
const fos=[{id:'fo',name:'Alisa',twentyMemberId:'wm'}];
const people=(n:number)=>Array.from({length:n},(_,i)=>({id:`p${i}`,name:`Person ${i}`,ownerMemberId:'wm',tags:[],contactType:[],tier:null}));
const draft=(n=4):CampaignDraft=>({name:'Test',podId:'pod',startDate:'2027-01-04',endDate:'2027-01-08',productInterest:['PHH'],defaultBatchSize:1,fos:[{id:'fo',batchSize:1}],personIds:people(n).map(p=>p.id),assignments:{},flows:[{id:'default',name:'Default',steps:outreachRecipe(1)}]});
describe('campaign-specific starter',()=>{
 it('builds two steps instead of eight for a short four-batch campaign',()=>{const d=draft();const fit=fitCampaignStarter(d,people(4),fos)!;expect(fit).not.toBeNull();expect(fit.draft.flows[0].steps).toHaveLength(2);expect(fit.calendar.valid).toBe(true);expect(outreachLimits(fit.draft,people(4),fos).default).toBe(2);});
 it('extends the channel recipe for a longer single-batch campaign',()=>{const d={...draft(1),endDate:'2027-01-15'};const fit=fitCampaignStarter(d,people(1),fos)!;expect(fit.draft.flows[0].steps).toHaveLength(10);expect(new Set(fit.draft.flows[0].steps.map(s=>s.id)).size).toBe(10);expect(fit.draft.flows[0].steps.at(-1)!.title).toBe('Close the loop');expect(fit.calendar.valid).toBe(true);});
 it('refuses no audience, unavailable owners and more first batches than days',()=>{expect(fitCampaignStarter(draft(0),[],fos)).toBeNull();expect(fitCampaignStarter(draft(6),people(6),fos)).toBeNull();expect(fitCampaignStarter(draft(),people(4).map(p=>({...p,ownerMemberId:'other'})),fos)).toBeNull();});
 it('reserves room for other contact groups when computing the step ceiling',()=>{const d=draft();d.flows[0].steps=outreachRecipe(2);d.flows.push({id:'clients',name:'Clients',steps:outreachRecipe(2)});d.assignments.p0='clients';const limits=outreachLimits(d,people(4),fos);expect(limits.default).toBe(2);expect(limits.clients).toBe(4);expect(buildCampaignCalendar(d,people(4),fos).valid).toBe(true);});
 it('rejects a 10,000-person overload before expanding date options',()=>{const d={...draft(10000),endDate:'2027-12-31'};d.flows[0].steps=outreachRecipe(60);const result=buildCampaignCalendar(d,people(10000),fos);expect(result.valid).toBe(false);expect(result.issues[0].title).toContain('batch size');});
 it('returns only fully covered starters across 60 size/window combinations',()=>{for(let n=1;n<=6;n++)for(let days=5;days<=14;days++){const d={...draft(n),endDate:`2027-01-${String(4+days).padStart(2,'0')}`};const fit=fitCampaignStarter(d,people(n),fos);if(fit){expect(fit.calendar.valid).toBe(true);for(const day of fit.calendar.days){const batch=fit.calendar.batches.filter(b=>b.dates.includes(day));expect(batch.length).toBeGreaterThan(0);expect(batch.length).toBeLessThanOrEqual(2);}}}});
});
