-- Sequences are no longer versioned. There is one editable plan per sequence; a step that has
-- open tasks is refused rather than moved, and what a task says is already frozen on the task
-- (Task.actionSnapshot), so an edit can never rewrite work an FO is holding.

-- 1. The plan moves onto the sequence, taken from whichever version was active.
ALTER TABLE "Sequence" ADD COLUMN "steps" JSONB NOT NULL DEFAULT '[]';
UPDATE "Sequence" s
   SET "steps" = v."steps"
  FROM "SequenceVersion" v
 WHERE v."id" = s."activeVersionId";

-- Any sequence without an active version falls back to its newest version.
UPDATE "Sequence" s
   SET "steps" = v."steps"
  FROM "SequenceVersion" v
 WHERE s."activeVersionId" IS NULL
   AND v."sequenceId" = s."id"
   AND v."version" = (SELECT MAX(v2."version") FROM "SequenceVersion" v2 WHERE v2."sequenceId" = s."id");

-- 2. An enrollment remembers the step it last generated by id, not only by index, so editing
--    the plan above it cannot make it skip or repeat a touch.
ALTER TABLE "Enrollment" ADD COLUMN "currentStepId" TEXT;
UPDATE "Enrollment" e
   SET "currentStepId" = t."stepId"
  FROM (SELECT DISTINCT ON ("enrollmentId") "enrollmentId", "stepId"
          FROM "Task" ORDER BY "enrollmentId", "stepIndex" DESC) t
 WHERE t."enrollmentId" = e."id";

-- 3. Drop the version links and the table.
ALTER TABLE "Task" DROP CONSTRAINT IF EXISTS "Task_sequenceVersionId_fkey";
ALTER TABLE "Enrollment" DROP CONSTRAINT IF EXISTS "Enrollment_sequenceVersionId_fkey";
ALTER TABLE "Sequence" DROP CONSTRAINT IF EXISTS "Sequence_activeVersionId_fkey";
DROP INDEX IF EXISTS "Task_sequenceVersionId_idx";
DROP INDEX IF EXISTS "Enrollment_sequenceVersionId_idx";
DROP INDEX IF EXISTS "Sequence_activeVersionId_key";
ALTER TABLE "Task" DROP COLUMN IF EXISTS "sequenceVersionId";
ALTER TABLE "Enrollment" DROP COLUMN IF EXISTS "sequenceVersionId";
ALTER TABLE "Sequence" DROP COLUMN IF EXISTS "activeVersionId";
DROP TABLE IF EXISTS "SequenceVersion";
